kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alpha-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-mysql
spec:
  replicas: 4
  template:
    metadata:
      labels:
        run: hello-mysql
    spec:
      containers:
      - name: hello-mysql
        image: hello-mysql:latest
        env:
        - name: HELLO_MESSAGE
          value: Hello whole world!
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /hello-mysql-volume
          name: hello-volume
      volumes:
      - name: hello-volume
        persistentVolumeClaim:
          claimName: alpha-claim
