kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - name: epmd
          containerPort: 4369
          protocol: TCP
        - name: amqp
          containerPort: 5672
          protocol: TCP
        - name: dist
          containerPort: 25672
          protocol: TCP
        - name: stats
          containerPort: 15672
          protocol: TCP
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: rabbit
        - name: RABBITMQ_DEFAULT_PASS
          value: rabbit
        - name: RABBITMQ_MANAGER_PORT_NUMBER
          value: '15672'
  strategy:
    type: Recreate
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - name: epmd
    protocol: TCP
    port: 4369
    targetPort: epmd
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: amqp
  - name: dist
    protocol: TCP
    port: 25672
    targetPort: dist
  - name: stats
    protocol: TCP
    port: 15672
    targetPort: stats
  selector:
    app: rabbitmq
  clusterIP: None
